service: gajimarket-api
runtime: nodejs20
instance_class: F1
entrypoint: node dist/bin/www.js

env_variables:
  NODE_ENV: 'production'
  PORT: 3000
  CLOUD_HOST: /cloudsql/winged-woods-442503-f1:asia-northeast3:codelab
  CODELAB_PORT: 5432
  CODELABDB: 'postgres'
  CODELAB_USER: 'codelab'
  CODELAB_PW: 'codelab1234'
  CODELAB_SCHEMA: 'team4'
  EMAIL_SERVICE: 'gmail'
  ADMIN_USER: 'hyung9683@gmail.com'
  ADMIN_PASSWORD: 'vfpcqppbmadpwcde'
  ADMIN_HOST: 'smtp.gmail.com'
  ADMIN_PORT: 587
  FRONT_PORT: 5173
  LOG_LEVEL: 'debug'
  KAKAO_API_KEY: '92d306357d9aa2dec212cf212a448853'
  REDIRECT_LOCAL_URI: 'http://localhost:3000/auth/kakao'
  REDIRECT_FRONT_URI: 'http://localhost:5173/auth/kakao'
  TOKEN_KEY: 'GajiMarket_KEY'
  BUCKET_NAME: 'codelab_gajigaji'
  GOOGLE_SERVICE_KEY: 'b70978f33a227df3b300ecf2e6c98ba28df962f5'
  GOOLE_PROJECT_ID: 'code-lab-it-lbstech'
  GOOGLE_APPLICATION_CREDENTIALS: '.\src\config\winged-woods-442503-f1-86741740a21e.json'


handlers:

 - url: /auth/.*
   script: auto
   secure: always
   
 - url: /map/.*
   script: auto
   secure: always

 - url: /product/.*
   script: auto
   secure: always

 - url: /navigation/.*
   script: auto
   secure: always

 - url: /api/.*
   script: auto
   secure: always

 - url: /mypage/.*
   script: auto
   secure: always

 - url: /notifications/.*
   script: auto
   secure: always

 - url: /mypage_love/.*
   script: auto
   secure: always

 - url: /use/.*
   script: auto
   secure: always
   
 - url: /api/mypage_sell/.*
   script: auto
   secure: always
   
 - url: /api/mypage_buy/.*
   script: auto
   secure: always

 - url: /api/mypage_keyword/.*
   script: auto
   secure: always


 - url: /.*
   script: auto
   secure: always
 
 






